### PR TITLE
PDP-11 backend WIP

### PR DESCRIPTION
**Pull request by shattered**
Experimental backend for DEC PDP-11 and compatible systems, targets CPUs with EIS feature running RT-11 V5.  Not complete (32-bit division routines missing) but does pass most of test suite.   I have used some tricks from http://www.telegraphics.com.au/sw/info/lcc-pdp11.html as well.

Native assembler (MACRO-11) does not handle long labels or underscore chars in them, but portable replacement https://gitlab.com/Rhialto/macro11 does.   Neither supports relative jump expansion; macros in longjmp.mac are a workaround and backend emits them plus a few macros from RT-11 system macro library (SYSMAC.SML).

There is also a portable linker (https://github.com/nzeemin/pclink11), but no portable RT-11 simulator; have to use full system simulator (SIMH).

### CODE REVIEW

**Comment by davidgiven** [comment]
That's fantastic news --- thanks very much! I'm impressed you managed to wade through my undocumented backend architecture _and_ my only-nominally documented programming language to make this work...

I've been wanting a PDP11 backend but haven't read up on the architecture yet. After my adventures with the 6502 I have in fact been wondering whether an additional abstraction layer to work with CISC architectures would be useful. But I don't know how that would work currently.

I haven't gone through your code yet, but a checkout shows that simhtest is missing. I assume that's not checked in because it needs a full VM to run. I'd very much like to have integrated compiler tests, but that needs a simulator, and simh is too heavyweight for that. It may be feasible to pull the CPU emulation engine out of simh to do enough emulation of simple binaries to run the tests, but it looks like apout already has this --- do you know if apout supports your version of the CPU? http://puszcza.gnu.org.ua/software/apout/

**Comment by shattered** [comment]
Thanks -- this was an interesting challenge.   I've started with a rather more obscure target, but PDP-11 is somewhat more useful -- several Soviet home/educational systems use this architecture (e.g. https://en.wikipedia.org/wiki/UKNC) and there is a small homebrew/demo scene.

simhtest doesn't really exist, I've been copying compiled object files manually into SIMH.  apout does support EIS, but SIMH has known good CPU emulation code so I'd go with that.

**Comment by davidgiven** [comment]
I've just imported apout (along the principle that it's complete and at least claims to work) and macro11 into the pdp11 branch. However, I'm now getting second thoughts. The apout simulates a.out binaries, but macro11 and pclink11 assume RT-11. I've had a look for the RT-11 executable format and they look pretty complex (multiple loadable modules).

So the choices are either: (a) use the simh core to write a simple simulator for RT-11 executables, only supporting console output; (b) write an assembler-loader for v7 executables which can be loaded into apout. (I've had a look at the v7 toolchain and while ld is in C and should be easy to port, as is in PDP-11 assembler. Sadly.) My choice would be (b) as I like Unix and I know how to write assemblers, but that locks Cowgol into making Unix v7 executables, and if people (i.e. you) actually want RT-11 executables, this doesn't help.

It looks like in real life, people use GNU binutils to make PDP-11 binaries, but that involves compiling binutils from source and I don't really want to go there...

**Comment by shattered** [comment]
Test suite doesn't really need an OS, does it?   It only needs to print to the terminal.

**Comment by davidgiven** [comment]
Yes, but there still needs to be some kind of binary environment, and I'd rather use a real target environment for this than create one just for the tests as that means less maintenance. But that's my problem, not yours...

**Comment by davidgiven** [comment]
I merged your branch into the pdp11 branch, along with apout, macro11 and a very simple linker I found but haven't tried yet; it's now integrated into the build system (I had to fix a few things). Builds fail with unmatched instruction errors due to division and remainders not being present. But it should help, at least.

**Comment by shattered** [comment]
Cool.   I've seen one other test compile failure:

error: tests/recordinitialisers.test.cow: 34: out of order static initialisation

plus two runtime failures in tests/interfaces.test.cow and tests/records.test.cow

**Comment by davidgiven** [comment]
I found (and fixed) a small bug where the cowfe and cowbe ArchAlignUp procedures weren't the same, which was causing those errors due to inconsistent structure layout. Ideally I should refactor so that these procedures are defined in only one place.

**Comment by davidgiven** [comment]
I managed to get the integration done! Unfortunately I couldn't find a RT11 usermode simulator, so I went for V7 Unix instead (using apout). But everything works, including building the compiler for the PDP11, and I smoke tested it by compiling a trivial program with the PDP11 compiler.

Unfortunately the one bit which doesn't work is my new assembler on the PDP11. It relies on a writable text segment, and V7 Unix prohibits this. I'll have to fix that but I'm going to merge things for now.

I had to make some backend changes, but most of the changes were because I didn't understand something you were doing deliberately and I ended up changing them back. There were some register allocation issues which caused problems which I fixed. There's plenty of scope for improving the generated code but that will actually be quite hard due to poor support in the code generator for addressing modes. I'm going to have to work on this --- there's a pile of code in the 6502 backend which sort of works, but it's a pain to work with and I need to make this a lot easier. The PDP11 backend will absolutely do for now. Thank you very much for this! If you feel like doing any more, they will be greatfully received...

**Comment by shattered** [comment]
Cool, and thanks for merging this.   There are a few ideas used by lcc codegen that should be easy to port (use bit test insn, for example), too.

**Pull request merged**
